# META: GPU_TYPE=L40s
#SBATCH --partition=preempt
#SBATCH --nodes=1
#SBATCH --gres=gpu:4
#SBATCH --cpus-per-gpu=4
#SBATCH --mem-per-gpu=48G
#SBATCH --time=7-00:00:00
#SBATCH --constraint=l40s
#SBATCH --requeue
